spring:
  application:
    name: product-service
  datasource:
    url: jdbc:h2:mem:productdb
    username: sa
    password: password
product-service:
  feature-flags:
    enable-discount: false
  catalog:
    refresh-rate-seconds: 3600